version: '2'
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  odoo14:
    image: odoo:14
    depends_on:
      - db
    ports:
      - "8069:8069"
#    tty: true
#    command: -- --dev=reload
#    command: odoo scaffold martinsam_module /mnt/extra-addons/custom_module
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./addons:/mnt/extra-addons
      - ./enterprise-14.0:/mnt/enterprise-addons
      - ./etc:/etc/odoo
      - ./data_dir:/var/lib/odoo/.local/share/Odoo
    restart: always             # run as a service
